[theme]
base = "light"
primaryColor = "#6C4AB6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f2f2f2"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501