[firebase]
apiKey = "AIzaSyBSpwzSf8hXxb4rBk-u8JPyX7Ha4kGoS8o"
authDomain = "mountainmedicine-6e572.firebaseapp.com"
projectId = "mountainmedicine-6e572"
storageBucket = "mountainmedicine-6e572.firebasestorage.app"
messagingSenderId = "1081705872512"
appId = "1:1081705872512:web:0ddf126c4737e47fd9ba65"

[openai]
api_key = "ZjNsOZvSPvP8SkHypqwuWXrXJnpZxDTEF56eodm7krLoptgw4bKt7T3rvymyJndF94gddNAepjT3BlbkFJh47G-G7paJCWf7nqdvyrXm4tegSM35Cq-u45FlqTN8wT8slsdqUAVY2qKgk38VpvZ0SXzcBp0A"

[firebase_admin]
type = "service_account"
project_id = "mountainmedicine-6e572"
private_key_id = "7945b853735ae7418e220f38888be120233240b3"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCStyBh6DJQGZQ1
kFzgUSnNBr1dK0sdQdX8CyqTJo+6UyH0QirSFQPqNLYfpdq8GuGYTdLBFUJgXe4a
q7wTgDfGUgUlfnqw5HBIvoL1s6YTqU1uofAPRYvjO2xTfG2kpqcFGLi/vT1yRWNZ
9AB9L8otxyBQ2BwTnaLRMniOoUSVIalDfCflYrBtFEHTyi8qSifakoNk7Ir7MiGf
WLnk04zM2Qp+At7+z/uSsLUpgxiB9rmi3LlptilvxuUsMj6IkhQ7Yj8ux8tSzFKl
A0usDDksEAYJSiMCKlrHlqNOXkI/0zedsXbYhqcAnoLOQmtWQmRdw4scDISJg1ow
ZkTH5iG1AgMBAAECggEACPuaiWFoBTSlDlODWuj1QXxGZ1gxfj4r7cWO6tlgpu8/
RAncvntIFP9QYFHYDuN+yQOzd0bH3IfGaTkhvThA500EdiYkjm8/ewtjustFTEJg
fzkog32GAgNpz5cYd802qtlM5HvKcZQ92pcrLtRYfA2LVQ/U8OmE+2ssQPVZnN94
kvy1JPtdhZYszlZ+O1eQH40yn3l7UG9DKc4NXO2XQnvc2o8zWVy+bqhDj1o+sdNx
IVV0xJI79xg8rwHzTAVvr8KZKQWlTPlg251Kjuzb4WTQHy9oiMX1kMo1lkRodEGD
LXYAl426GjfIixrZthlMZsMkHWks1hkCejxr6V4XoQKBgQDIzt4Gn0wHYVO976T9
SCTzhBxXl1ABfGy8nAE45mLPpBPnO1/kT139R2vnLdMY4cjG0fF7Yg2yp/d3hLHL
PwD/CXcFaZ6TxivfC0gz2o2v8HMTKPp+FGkOCNX9tGlBBpj4e0VWmzKpNAb/Op3W
AI+SXrCLilgZNvlZF8PRb36HlQKBgQC7Cjg+puMrMxUVLAiIrUjlpQaiK/l+2fOK
tBmXhuY+x1nzBxZQHSh/v8UMciSx8LI1Ddd8D/ZkeyR7TAwsMgwQXvV8igE9+YrB
K5fVOYIkekc6YnyAnuOQogkzKbPXR+92Tn2q2GSo3rEJzTfJDXoidZmXPPCEsndA
zNOAuCwpoQKBgQCcfvPzz0POYKCF3vUDW61IhwYbkVYNwm1v1FjzgkExt5q3U8OY
x+3lDTtfsIva0WPK5yU+Vh18xYCMCcMSNejN2g+DDVxDqGbabg14M/TGUCsunHoT
tk5lXKeBEJAS2FRxGojgRRWHXn+xe3o0pL0/gkIujcO46uoK8AVw/GZsvQKBgQCh
C8qj/3RIZQJ5KWHrtTC4MuDEUBLSK33sZuhGNSwYz/NeMzL+Ji0R2iAjeECqSfJX
hiSNOP1RRUqDM1aj0y/aBLlg0z8AitXzP8LLIGozWGnuFpDW+ng8t5guSnEEI3dH
KYxAx3Pch2puYxnubkFEXHez5g++YiAWVoaiJXI5IQKBgGA0qVjQanXEqUPm9jtD
ADl6IuKhvSMcsbAEUFwZ9ecmE8W5Im+Se5ZTnQ9GQ7vV60k5BXCvaWGhPgIT8ldt
VStuLTu9DFDqIGpHjYgEAHBjakoLBY7EORJh12F9fMAQBS4hcJJ0R5LtN2oPhQ2L
489IK/d6KwnCG1oqVXeKTIRp
-----END PRIVATE KEY-----"""

client_email = "firebase-adminsdk-fbsvc@mountainmedicine-6e572.iam.gserviceaccount.com"
client_id = "104184079301366010340"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40mountainmedicine-6e572.iam.gserviceaccount.com"
universe_domain = "googleapis.com"